
title = "I'm Gary Nguyen"
author = "Gary Nguyen"
description = "I'm a data scientist and NLP practitioner based in NYC"
profilePicture = "images/profile_new.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
contactFormAction = "https://formspree.io/f/myylepll"
# Google Analytics
googleAnalytics = "UA-197094413-1"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2006-01-02"
indexDateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"


[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/hnguyen1174/"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/hnguyen1174"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:han2114@columbia.edu"